# This workflow will execute AmPyfier on the unit.smallbanktest test suite

name: Amplify unit.smallbanktest

on:
  workflow_dispatch:
    inputs:
      start_commit:
        description: "commit to start with when using AmPyfier only on changed files"
        required: false
        default: ""
      end_commit:
        description: "commit to end with when using AmPyfier only on changed files"
        required: false
        default: ""
      size:
        description: "size parameter to pass to AmPyfier"
        required: false
        default: "20"

jobs:
  amplify_examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
      - name: Amplify unit.smallbanktest
        uses: SchoofsEbert/AmPyfier_actions@main
        with:
          token: ${{ secrets.AMPYFIER_TOKEN }}
          python-version: ""
          test: "unit.test_smallbank"
          project_dir: "."
          arguments: --size ${{ github.event.inputs.size }}
          python_path: "test"
          start_commit: ${{ github.event.inputs.start_commit }}
          end_commit: ${{ github.event.inputs.end_commit }}
      - name: Commit amplified tests
        run: |
          git config --global user.email "ampyfier@bot.com"
          git config --global user.name "AmPyfier Bot"
          git add unit
          git commit -m "Amplified tests"
      - name: Push Amplified tests
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Collect report
        uses: actions/upload-artifact@v2
        with:
          name: smallbanktest_reports
          path: ampyfier_reports

